# Generated by Django 5.1.4 on 2025-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
