# Generated by Django 5.1.4 on 2025-01-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_seller_city_seller_pincode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tiffin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="tiffins/")),
                ("ingredients", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
